FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    YOLO_CONFIG_DIR=/app/.config \
    LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64:$LD_LIBRARY_PATH

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.10 \
    python3-pip \
    libgl1 \
    libglib2.0-0 \
    ffmpeg \
    curl \
    && curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz | tar xvz -C /usr/local/bin \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app/.config/Ultralytics && chmod -R 777 /app/.config

COPY requirements-vast.txt .
RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir -r requirements-vast.txt "tensorrt-cu12>=7.0.0,!=10.2.0"

COPY client/ ./client/
COPY models/ ./models/
COPY server/ ./server/
COPY main.py .

EXPOSE 8000

# CMD sh -c "ngrok config add-authtoken $NGROK_AUTHTOKEN && \
#     ngrok http 8000 > /dev/null & \
#     uvicorn main:app --host 0.0.0.0 --port 8000"

# CMD sh -c "... [ ! -f models/best.engine ] && yolo export model=models/best.pt format=engine half=True device=0; uvicorn main:app ..."
#     yolo export model=models/best.pt format=engine half=True device=0

CMD sh -c "if [ ! -f models/best_rtx3060.engine ]; then \
        echo 'Engine not found, generating...' && \
        yolo export model=models/best.pt format=engine half=True device=0 imgsz=800 && \
        mv models/best.engine models/best_rtx3060.engine; \
    fi && \
    ngrok config add-authtoken $NGROK_AUTHTOKEN && \
    ngrok http 8000 > /dev/null & \
    uvicorn main:app --host 0.0.0.0 --port 8000"